---
  - name: add nodejs ppa
    apt_repository: repo='ppa:chris-lea/node.js'
    sudo: yes

  - name: apt | cache | update
    apt: update_cache=yes
    when: do_install|bool

  - name: girder | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - curl
      - g++
      - git
      - libffi-dev
      - make
      - python-dev
      - python-pip
      - nodejs
    when: do_install|bool

  - name: girder | service | stop
    service:
        name: girder
        state: stopped
    ignore_errors: true
    when: stop_services|bool


  - name: girder | install root | delete
    file:
        path: "{{ girder_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: girder | data root | delete
    file:
        path: "{{ girder_data_root }}"
        state: absent
    when: remove_data_root|bool

  - name: girder | install parent | create
    file:
        path: "{{ girder_install_parent }}"
        state: directory
    when: do_install|bool

  - name: girder | data root | create
    file:
        path: "{{ girder_data_root }}"
        state: directory
        mode: 0755
    when: do_install|bool

  - name: girder | data root | owner | set
    file:
        path: "{{ girder_data_root }}"
        state: directory
        group: "{{ girder_group }}"
        owner: "{{ girder_user }}"
        mode: 0775
    when: do_install|bool

  - name: girder | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ girder_git_work_dir }}/"
        "{{ girder_install_root }}"
    when: do_install|bool

  - name: girder | log | perms | set
    file:
        path: "{{ girder_install_root }}/logs"
        mode: 0755
        state: directory
    when: do_install|bool

  # Minerva depends on cryptography,  which requires a newer version of
  # cffi.  This task is a temporary fix until we can bump the version in
  # girder.
  - name: Update cffi version for minerva
    replace:
      dest: "{{ girder_install_root }}/requirements.txt"
      regexp: 'cffi==0\.8\.6'
      replace: 'cffi==1.3.0'


  - name: girder | pip
    pip: requirements={{ girder_install_root }}/requirements.txt
    when: do_install|bool

    # Note: this is required to run the girder
    # module in later configuration steps
  - name: girder | pip | girder_client
    pip:
      name: girder-client
      version: 1.0.1
    when: do_install|bool

  - name: grunt-cli | install
    npm:
        name: grunt-cli
        global: yes
    when: do_install|bool

  - name: girder | conf | owner | set
    file:
        recurse: yes
        path: "{{ girder_install_root }}"
        group: "{{ girder_group }}"
        mode: 0755
        owner: "{{ girder_user }}"
    when: do_install|bool

  - name: girder | conf | girder.local.cfg | generate
    template:
        src: girder.local.cfg.j2
        dest: "{{ girder_install_root }}/girder/conf/girder.local.cfg"
        mode: 0644
    when: do_install|bool
