- hosts: mongo
  sudo: yes
  roles:
    - role: mongodb
      state: started

- hosts: rabbitmq
  sudo: yes
  roles:
    - role: rabbitmq
      state: started

- hosts: girder
  sudo: yes
  vars:
    - base_dir: /opt
  roles:
    - role: romanesco
      rabbitmq_ansible_group: rabbitmq
      state: started

    - role: girder
      mongodb_ansible_group: girder
      girder_admin_user: girder
      girder_admin_password: letmein
      state: started

    - role: minerva

  tasks:
    - name: Install minerva and romanesco as girder plugins
      command: "girder-install plugin -s -f {{base_dir}}/minerva {{base_dir}}/romanesco"


# Configure plugins and girder
- hosts: girder
  sudo: yes
  tags:
    - test
  tasks:
    - wait_for:
        port: 8080
        delay: 5

    - name: Create an 'Admin' user
      girder:
        port: 8080
        user:
          firstName: "Admin"
          lastName: "Admin"
          login: "admin"
          password: "letmein"
          email: "admin@example.com"
          admin: yes
        state: present

    - name: Activate Plugins
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        plugins:
          - romanesco
          - minerva
        state: present

    - name: Create assetstore directory
      file:
        path: "/opt/data"
        owner: "girder"
        group: "girder"
        state: directory

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/opt/data"
          current: true
        state: present


    - name: Restart Minerva
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        put:
          path: "system/restart"
