- hosts: mongo
  sudo: yes
  roles:
    - role: mongodb
      state: started

- hosts: rabbitmq
  sudo: yes
  roles:
    - role: rabbitmq
      state: started

- hosts: girder
  vars:
    base_dir: /opt
    girder_user: "girder"
    girder_group: "girder"
  pre_tasks:
    - name: Create virtualenv folder
      file:
        path: "{{venv_root}}"
        state: directory
        mode: 0775
      sudo: yes

  roles:
    - role: girder
      mongodb_ansible_group: girder
      girder_admin_user: girder
      girder_admin_password: letmein
      girder_version: "{{ lookup('file', '../.girder-version') }}"
      state: started
      sudo: yes

    - role: minerva
      minerva_version: "{{ lookup('pipe', 'git rev-parse --abbrev-ref HEAD 2>/dev/null || echo master') }}"
      sudo: yes

  tasks:
    - name: Set permissions on virtualenv folder
      file:
        path: "{{venv_root}}"
        recurse: yes
        state: directory
        mode: 0775
        owner: "{{ girder_user }}"
        group: "{{ girder_group }}"
      sudo: yes

    - name: Install minerva as a girder plugin
      shell: ". {{venv_root}}/bin/activate && girder-install plugin -s -f {{base_dir}}/minerva"
      become: yes
      become_user: "{{girder_user}}"
      tags:
        - test
        - minerva-update

# Configure plugins and girder
- hosts: girder
  sudo: yes
  tags:
    - test
  tasks:
    - wait_for:
        port: 8080
        delay: 5

    - name: Create an 'Admin' user
      girder:
        port: 8080
        user:
          firstName: "Admin"
          lastName: "Admin"
          login: "admin"
          password: "letmein"
          email: "admin@example.com"
          admin: yes
        state: present

    - name: Activate Plugins
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        plugins:
          - minerva
        state: present

    - name: Create assetstore directory
      file:
        path: "/opt/data"
        owner: "girder"
        group: "girder"
        state: directory

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/opt/data"
          current: true
        state: present


    - name: Restart Minerva
      girder:
        port: 8080
        username: "admin"
        password: "letmein"
        put:
          path: "system/restart"
